version: "3.8"

services:
  backend1:
    build: .
    container_name: backend1
    restart: always
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=diabetes_db
      - DB_USER=admin
      - DB_PASS=password
    ports:
      - "5001:5000"

  backend2:
    build: .
    container_name: backend2
    restart: always
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=diabetes_db
      - DB_USER=admin
      - DB_PASS=password
    ports:
      - "5002:5000"

  backend3:
    build: .
    container_name: backend3
    restart: always
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=diabetes_db
      - DB_USER=admin
      - DB_PASS=password
    ports:
      - "5003:5000"

  api:
    build: .
    container_name: api
    restart: always
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=diabetes_db
      - DB_USER=admin
      - DB_PASS=password
    command: python app_api.py
    ports:
      - "5050:5050"

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - backend3

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: diabetes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    environment:
      DATABASE_URL: "postgres://admin:password@postgres-db:5432/diabetes_db"
      PGBOUNCER_POOL_MODE: transaction
    depends_on:
      - postgres-db
    ports:
      - "6432:6432"

volumes:
  postgres_data:

