services:
  postgres-master:
    image: postgres:14
    container_name: postgres-master
    restart: always
    environment:
      POSTGRES_DB: diabetes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=replica -c listen_addresses='*' -c password_encryption=md5
    networks:
      - db-network

volumes:
  postgres_master_data:

networks:
  db-network:
    driver: bridge
