version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    restart: always
    environment:
      - DB_HOST=pgbouncer
      - DB_NAME=diabetes_db
      - DB_USER=admin
      - DB_PASS=password
    ports:
      - "5000:5000"
    depends_on:
      - pgbouncer

  api:
    build: .
    container_name: api
    restart: always
    environment:
      - DB_HOST=pgbouncer
      - DB_NAME=diabetes_db
      - DB_USER=admin
      - DB_PASS=password
    command: python app_api.py
    ports:
      - "5050:5050"
    depends_on:
      - pgbouncer

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: diabetes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    command: postgres -c password_encryption=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    environment:
      DATABASE_URL: "postgres://admin:password@postgres-db:5432/diabetes_db"
      PGBOUNCER_POOL_MODE: transaction
    depends_on:
      - postgres-db
    ports:
      - "6432:6432"

volumes:
  postgres_data:

