services:
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    restart: always
    ports:
      - "8080:8080"
      - "5050:5050"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
